// <auto-generated />
using System;
using dEngage.Loyalty.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace dEngage.Loyalty.Schema.Migrations
{
    [DbContext(typeof(LoyaltyDbContext))]
    [Migration("20260903184551_AddRuleTemplate")]
    partial class AddRuleTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.AccountType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.HasIndex("TenantId", "ProgramId")
                        .HasDatabaseName("idx_account_types_tenant_program");

                    b.ToTable("account_types", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_admin_users_email");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_admin_users_tenant_id");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.CustomerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_type_id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("balance");

                    b.Property<string>("ContactKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_key");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly?>("TierExpiresAt")
                        .HasColumnType("date")
                        .HasColumnName("tier_expires_at");

                    b.Property<Guid?>("TierId")
                        .HasColumnType("uuid")
                        .HasColumnName("tier_id");

                    b.Property<DateOnly?>("TierPeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("tier_period_start");

                    b.Property<decimal>("TierQualifyingPts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tier_qualifying_pts");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("TierId");

                    b.HasIndex("TenantId", "ContactKey")
                        .HasDatabaseName("idx_customer_accounts_tenant_contact");

                    b.HasIndex("TenantId", "ContactKey", "AccountTypeId")
                        .IsUnique()
                        .HasDatabaseName("uq_customer_accounts_tenant_contact_accounttype");

                    b.ToTable("customer_accounts", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.EventInbox", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("EventId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("event_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("TenantId", "EventId");

                    b.ToTable("event_inbox", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.EventLog", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("EventId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("event_id");

                    b.Property<string>("ContactKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_key");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("TenantId", "EventId");

                    b.ToTable("event_log", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.LedgerEntry", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_account_id");

                    b.Property<decimal>("Delta")
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("delta");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_event_id");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("RuleId");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_ledger_entries_idempotency_key");

                    b.HasIndex("TenantId", "SourceEventId")
                        .HasDatabaseName("idx_ledger_entries_tenant_source_event");

                    b.HasIndex("TenantId", "CustomerAccountId", "CreatedAt")
                        .HasDatabaseName("idx_ledger_entries_tenant_account_date");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.OutboxEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("ContactKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dedup_key");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_outbox_event_id");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("idx_outbox_pending_next_attempt")
                        .HasFilter("status = 'pending'");

                    b.HasIndex("TenantId", "DedupKey")
                        .IsUnique()
                        .HasDatabaseName("ux_outbox_dedup")
                        .HasFilter("dedup_key IS NOT NULL");

                    b.ToTable("outbox_events", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("QualifyingAccountTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("qualifying_account_type_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("WarningDays")
                        .HasColumnType("integer")
                        .HasColumnName("warning_days");

                    b.HasKey("Id");

                    b.HasIndex("QualifyingAccountTypeId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_programs_tenant_id");

                    b.ToTable("programs", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.RewardDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acquisition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("acquisition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalCouponType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_coupon_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PointsAccountTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("points_account_type_id");

                    b.Property<decimal?>("PointsPrice")
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("points_price");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<Guid?>("StampAccountTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("stamp_account_type_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("PointsAccountTypeId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("StampAccountTypeId");

                    b.HasIndex("TenantId", "ProgramId")
                        .HasDatabaseName("idx_reward_definitions_tenant_program");

                    b.HasIndex("TenantId", "StampAccountTypeId")
                        .IsUnique()
                        .HasDatabaseName("ux_reward_definitions_active_stamp")
                        .HasFilter("acquisition = 'stamp_completion' AND is_active");

                    b.HasIndex("TenantId", "ProgramId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_reward_definitions_tenant_program_name");

                    b.ToTable("reward_definitions", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.RewardLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_type_id");

                    b.Property<int>("CompletionCount")
                        .HasColumnType("integer")
                        .HasColumnName("completion_count");

                    b.Property<string>("ContactKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid>("LedgerResetEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_reset_entry_id");

                    b.Property<Guid?>("RewardDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("reward_definition_id");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reward_type");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_event_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("RewardDefinitionId");

                    b.HasIndex("TenantId", "AccountTypeId", "SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_reward_log_source_event");

                    b.HasIndex("TenantId", "ContactKey", "Status")
                        .HasDatabaseName("idx_reward_log_tenant_contact_status");

                    b.ToTable("reward_log", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_from");

                    b.Property<DateTime?>("ActiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_to");

                    b.Property<string>("Calculation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("calculation");

                    b.Property<string>("Conditions")
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Limits")
                        .HasColumnType("jsonb")
                        .HasColumnName("limits");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<bool>("Stackable")
                        .HasColumnType("boolean")
                        .HasColumnName("stackable");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetAccountTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_account_type_id");

                    b.Property<string>("Template")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("template");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trigger");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.HasIndex("TargetAccountTypeId");

                    b.HasIndex("TenantId", "ProgramId", "Status")
                        .HasDatabaseName("idx_rules_tenant_program_status");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.RuleFireAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalculationSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("calculation_snapshot");

                    b.Property<string>("ConditionsSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions_snapshot");

                    b.Property<string>("ContactKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("LedgerEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_entry_id");

                    b.Property<decimal>("ResultingDelta")
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("resulting_delta");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<DateTime>("RuleVersion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rule_version");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_event_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RuleId", "CreatedAt")
                        .HasDatabaseName("idx_rule_fire_audit_tenant_rule_date");

                    b.HasIndex("TenantId", "SourceEventId", "RuleId")
                        .IsUnique()
                        .HasDatabaseName("ux_rule_fire_audit_source_event_rule");

                    b.ToTable("rule_fire_audit", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.StreakAppliedEvent", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("EventId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.HasKey("TenantId", "CampaignId", "EventId");

                    b.ToTable("streak_applied_event", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.StreakCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_from");

                    b.Property<DateTime?>("ActiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_to");

                    b.Property<string>("Conditions")
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetAccountTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_account_type_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trigger");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.HasIndex("TargetAccountTypeId");

                    b.HasIndex("TenantId", "ProgramId", "Status")
                        .HasDatabaseName("idx_streak_campaigns_tenant_program_status");

                    b.ToTable("streak_campaigns", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.StreakLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateOnly>("CompletedPeriod")
                        .HasColumnType("date")
                        .HasColumnName("completed_period");

                    b.Property<int>("CompletionNo")
                        .HasColumnType("integer")
                        .HasColumnName("completion_no");

                    b.Property<string>("ContactKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Periods")
                        .HasColumnType("integer")
                        .HasColumnName("periods");

                    b.Property<string>("RewardKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reward_kind");

                    b.Property<string>("RewardRef")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reward_ref");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_event_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CampaignId", "ContactKey", "CompletionNo")
                        .IsUnique()
                        .HasDatabaseName("ux_streak_log_completion");

                    b.ToTable("streak_log", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.StreakPeriodState", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("ContactKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_key");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<int>("AggCount")
                        .HasColumnType("integer")
                        .HasColumnName("agg_count");

                    b.Property<decimal>("AggSum")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("agg_sum");

                    b.Property<bool>("Met")
                        .HasColumnType("boolean")
                        .HasColumnName("met");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "CampaignId", "ContactKey", "PeriodStart");

                    b.HasIndex("TenantId", "CampaignId", "PeriodStart")
                        .HasDatabaseName("idx_streak_period_state_rule_period");

                    b.ToTable("streak_period_state", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.StreakProgress", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("ContactKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_key");

                    b.Property<int>("Completions")
                        .HasColumnType("integer")
                        .HasColumnName("completions");

                    b.Property<DateOnly?>("LastMetPeriod")
                        .HasColumnType("date")
                        .HasColumnName("last_met_period");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("StreakCount")
                        .HasColumnType("integer")
                        .HasColumnName("streak_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "CampaignId", "ContactKey");

                    b.ToTable("streak_progress", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.TenantApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HashedKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hashed_key");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("KeyPrefix")
                        .IsUnique()
                        .HasDatabaseName("uq_tenant_api_keys_prefix");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_tenant_api_keys_tenant_id");

                    b.ToTable("tenant_api_keys", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.TierDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<int>("GraceDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("grace_days");

                    b.Property<decimal>("MinPoints")
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("min_points");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<int?>("QualifyingDays")
                        .HasColumnType("integer")
                        .HasColumnName("qualifying_days");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_tier_definitions_program_name");

                    b.HasIndex("ProgramId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("uq_tier_definitions_program_sort_order");

                    b.HasIndex("TenantId", "ProgramId")
                        .HasDatabaseName("idx_tier_definitions_tenant_program");

                    b.ToTable("tier_definitions", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.TierUpgradeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FromTierId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_tier_id");

                    b.Property<decimal>("QualifyingPts")
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("qualifying_pts");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_event_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ToTierId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_tier_id");

                    b.HasKey("Id");

                    b.HasIndex("FromTierId");

                    b.HasIndex("ToTierId");

                    b.HasIndex("TenantId", "ContactKey")
                        .HasDatabaseName("idx_tier_upgrade_log_tenant_contact");

                    b.HasIndex("TenantId", "ContactKey", "SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_tier_upgrade_log_source_event");

                    b.ToTable("tier_upgrade_log", (string)null);
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.AccountType", b =>
                {
                    b.HasOne("dEngage.Loyalty.Schema.Entities.Program", "Program")
                        .WithMany("AccountTypes")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.AdminUser", b =>
                {
                    b.HasOne("dEngage.Loyalty.Schema.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.CustomerAccount", b =>
                {
                    b.HasOne("dEngage.Loyalty.Schema.Entities.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dEngage.Loyalty.Schema.Entities.TierDefinition", "Tier")
                        .WithMany()
                        .HasForeignKey("TierId");

                    b.Navigation("AccountType");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.LedgerEntry", b =>
                {
                    b.HasOne("dEngage.Loyalty.Schema.Entities.CustomerAccount", "CustomerAccount")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dEngage.Loyalty.Schema.Entities.Rule", "Rule")
                        .WithMany()
                        .HasForeignKey("RuleId");

                    b.Navigation("CustomerAccount");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.Program", b =>
                {
                    b.HasOne("dEngage.Loyalty.Schema.Entities.AccountType", "QualifyingAccountType")
                        .WithMany()
                        .HasForeignKey("QualifyingAccountTypeId");

                    b.Navigation("QualifyingAccountType");
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.RewardDefinition", b =>
                {
                    b.HasOne("dEngage.Loyalty.Schema.Entities.AccountType", "PointsAccountType")
                        .WithMany()
                        .HasForeignKey("PointsAccountTypeId");

                    b.HasOne("dEngage.Loyalty.Schema.Entities.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dEngage.Loyalty.Schema.Entities.AccountType", "StampAccountType")
                        .WithMany()
                        .HasForeignKey("StampAccountTypeId");

                    b.Navigation("PointsAccountType");

                    b.Navigation("Program");

                    b.Navigation("StampAccountType");
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.RewardLog", b =>
                {
                    b.HasOne("dEngage.Loyalty.Schema.Entities.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dEngage.Loyalty.Schema.Entities.RewardDefinition", "RewardDefinition")
                        .WithMany()
                        .HasForeignKey("RewardDefinitionId");

                    b.Navigation("AccountType");

                    b.Navigation("RewardDefinition");
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.Rule", b =>
                {
                    b.HasOne("dEngage.Loyalty.Schema.Entities.Program", "Program")
                        .WithMany("Rules")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dEngage.Loyalty.Schema.Entities.AccountType", "TargetAccountType")
                        .WithMany()
                        .HasForeignKey("TargetAccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("TargetAccountType");
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.StreakCampaign", b =>
                {
                    b.HasOne("dEngage.Loyalty.Schema.Entities.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dEngage.Loyalty.Schema.Entities.AccountType", "TargetAccountType")
                        .WithMany()
                        .HasForeignKey("TargetAccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("TargetAccountType");
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.TenantApiKey", b =>
                {
                    b.HasOne("dEngage.Loyalty.Schema.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.TierDefinition", b =>
                {
                    b.HasOne("dEngage.Loyalty.Schema.Entities.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.TierUpgradeLog", b =>
                {
                    b.HasOne("dEngage.Loyalty.Schema.Entities.TierDefinition", "FromTier")
                        .WithMany()
                        .HasForeignKey("FromTierId");

                    b.HasOne("dEngage.Loyalty.Schema.Entities.TierDefinition", "ToTier")
                        .WithMany()
                        .HasForeignKey("ToTierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromTier");

                    b.Navigation("ToTier");
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.CustomerAccount", b =>
                {
                    b.Navigation("LedgerEntries");
                });

            modelBuilder.Entity("dEngage.Loyalty.Schema.Entities.Program", b =>
                {
                    b.Navigation("AccountTypes");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
