<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\dEngage.Loyalty.Schema\dEngage.Loyalty.Schema.csproj" />
    <ProjectReference Include="..\dEngage.Loyalty.Shared\dEngage.Loyalty.Shared.csproj" />
    <ProjectReference Include="..\dEngage.Loyalty.Engine.Framework\dEngage.Loyalty.Engine.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="UUIDNext" Version="4.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
